# Meeting Agent Configuration File
# This file contains non-sensitive application settings
# Secrets (API keys, passwords) are stored in environment variables

# OpenAI Configuration
openai:
  transcription_model: "whisper-1"
  summarization_model: "gpt-4"
  max_tokens: 1500

# Email Configuration  
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  daily_summary_time: "22:00"

# Web Interface Configuration
web:
  host: localhost
  port: 5002
  debug: false

# Database Configuration
database:
  path: "data/meetings.db"
  url: sqlite:///data/meetings.db

# Audio Recording Configuration
audio:
  sample_rate: 44100
  channels: 1
  format: 16bit
  chunk_size: 1024

# Logging Configuration
logging:
  level: INFO
  file: logs/meeting_agent.log

# Meeting Configuration
meeting:
  max_duration_hours: 8
  auto_save_interval_seconds: 30
  transcript_chunk_size: 1000

# Transcription Configuration
transcription:
  process_interval_seconds: 3.0
  min_chunks_to_process: 2
  min_file_size_bytes: 1000

# Cost Tracking
cost:
  whisper_per_minute: 0.006  # USD per minute